version: '3'
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:80
    volumes:
      - ./app:/var/www/html
      - ./app/.htaccess:/usr/local/apache2/htdocs/.htaccess

  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: api_correios
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql
    ports:
      - 3306:3306
